language: python
python:
  - 2.7
notifications:
  email: false
env:
  global:
    - PSQL=postgres://postgres:@localhost:5432/debris
services:
  - postgres
  - memcached
  - redis-server
before_script:
  - psql -U postgres -c 'create database debris;' 
  - psql debris -U postgres -f tests/demo.sql
  - pip install Tornado python-binary-memcached redis coveralls tornpsql
script:
  - coverage run -m unittest discover -s tests
after_success:
  coveralls
