language: python
python:
  - 2.7
  - pypy
  - 3.3
services: 
  - postgres
  - redis
before_script:
  - pip install Tornado
  - nohup bash -c "python -m tests.server &"
  - sleep 4
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3* ]]; then python -m unittest discover -s tests/3/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7* ]]; then python -m unittest discover -s tests/2/; fi
