language: python
python:
  - 2.7
notifications:
  email: false
env:
  global:
    - TORNPSQL=postgres://postgres:@127.0.0.1:5432/debris
services:
  - memcached
  - redis-server
before_script:
  - pip install Tornado python-binary-memcached redis coveralls tornpsql
  - pip install --upgrade git+https://github.com/stevepeak/tornpsql@master
  - psql -U postgres -c 'create database debris;' 
  - psql debris -U postgres -f tests/demo.sql
script:
  - coverage run -m unittest discover -s tests
after_success:
  - coveralls
