language: python
python:
  - 2.7
  - pypy
services:
  - redis-server
  - memcached
before_script:
  - pip install Tornado python-binary-memcached redis coveralls
script:
  - coverage run -m unittest discover -s tests
after_success:
  coveralls
