language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
services: 
  - postgres
  - redis
before_script:
  - pip install Tornado
  - nohup bash -c "python -m tests.server &"
  - sleep 4
script:
  - python -m unittest discover -s tests
